server:
  port: 8092

spring:
  application:
    name: patientRecords

  datasource:
    url: jdbc:mysql://heealthsyncdb.cjwgky6gwqig.eu-north-1.rds.amazonaws.com:3306/patient_record_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: Thushari1002
#    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # update tables
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
