name: CI/CD Pipeline to Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 21 for Maven
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Step 3: Run Maven tests
      - name: Run Maven tests
        run: mvn test

      # Step 4: Build the project using Maven
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # Step 5: Authenticate Docker to GitHub Container Registry (GHCR)
      - name: Authenticate to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Step 6: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/nethmipathirana/patient-records-ms:latest .

      # Step 7: Check if the JAR file exists in the Docker image
      - name: Check if JAR file exists in Docker image
        run: |
          # Run the container and check if the JAR file exists in the /app directory
          docker run --rm ghcr.io/nethmipathirana/patient-records-ms:latest ls /app
          if [ "$(docker run --rm ghcr.io/nethmipathirana/patient-records-ms:latest ls /app | grep app.jar)" == "" ]; then
            echo "ERROR: app.jar not found in the Docker image."
            exit 1
          else
            echo "app.jar found in the Docker image."
          fi

      # Step 8: Push Docker image to GHCR
      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/nethmipathirana/patient-records-ms:latest
          echo "Pushed new Docker image."
